### ISSUE TITLE
Default cursor focus to the code view for easy navigation

### ISSUE THREAD

**Issue by jondrummond-codeo** [fluffynuts/diff-buddy#2]
When navigating between changes, it would be good if the default cursor focus would be in the code view, not the comment view to make it easier to use page up / down without having to manually put focus on the code pane.

**Comment by fluffynuts** [comment]
The decision to focus the comments section was on purpose, after feedback from Rohland - in a lot of cases, the diff fits into one page, so one can simply type, f2, f2, type, f2, type, etc... otherwise one would have to focus the comments box every time.

So what I've done instead is take a little inspiration from LazyGit - now when the comments box is focused, PageUp and PageDown won't scroll the comments (which are probably all going to fit in the box anyway), but will, instead, scroll the diff view.

The default is to scroll by 5 lines at a time, but you can control how much to scroll by:
- by specifying `--page-size` on the command-line
- by setting an environment variable `PAGE_SIZE`
	- this will be overridden by `--page-size`

if you find you're often specifying `--page-size` to the same number (eg `10`), then add something like:
```
export PAGE_SIZE=10
```
to your ~/.bashrc
